blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Question
    url: https://github.com/aws/aws-sdk-kotlin/discussions/new/choose
    about: Please ask and answer questions as a discussion thread